# Generated by Django 4.0.3 on 2023-01-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesiton_text',
            new_name='question_text',
        ),
    ]
